version: "3"
services:
  server:
    build: ./
    image: server
    ports:
      - 80:80
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    volumes:
      - ./serverless:/usr/local/zappa_server/
    command: >
      sh -c "pipenv run python manage.py migrate &&
             pipenv run python manage.py runserver 0.0.0.0:8080"

  mysql:
    image: mysql
    container_name: mysql_server
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'serverless'
      MYSQL_PASSWORD: 'somepassword'
      MYSQL_ROOT_PASSWORD: "somepassword"
    volumes:
      - ./sql/db-storage:/var/lib/mysql