version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - server
    restart: always
    environment:
      DOMAINS: 'storage.sirileepage.com -> http://server:80'
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
  server:
    build: ./
    image: storage-server
    stdin_open: true
    tty: true
    volumes:
      - ./serverless:/usr/local/serverless/serverless/
    command: >
      sh -c "pipenv run python manage.py makemigrations &&
             pipenv run python manage.py migrate &&
             pipenv run python manage.py runserver 0.0.0.0:80"
  test:
    build: ./
    image: storage-server
    stdin_open: true
    tty: true
    volumes:
      - ./serverless:/usr/local/serverless/serverless/
    command: >
      sh -c "pipenv run coverage run --source='.' manage.py test && pipenv run coverage html"
