version: "3"
services:
  https:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - django
    restart: always
    depends_on:
      - django
    environment:
      DOMAINS: 'storage.sirileepage.com -> http://django'
      STAGE: local
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
  django:
    build: ./
    image: storage-server
#    ports:
#      - '80:80'
#      - '443:80'
    stdin_open: true
    tty: true
    volumes:
      - ./serverless:/usr/local/serverless/serverless/
    command: >
      sh -c "pipenv run python manage.py makemigrations &&
             pipenv run python manage.py migrate &&
             pipenv run python manage.py runserver 0.0.0.0:80"
  test:
    build: ./
    image: storage-server
    stdin_open: true
    tty: true
    volumes:
      - ./serverless:/usr/local/serverless/serverless/
    command: >
      sh -c "pipenv run coverage run --source='.' manage.py test && pipenv run coverage html"
