version: "3"
services:
  https:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'storage.sirileepage.com -> http://django'
      STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
  django:
    build: ./
    image: storage-server
    ports:
      - '8080:80'
    stdin_open: true
    tty: true
    volumes:
      - ./serverless:/usr/local/serverless/serverless/
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:80"
    depends_on:
      - db
      - https

  db:
    image: postgres
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
#    ports:
#      - 5400:5432
    environment:
      POSTGRES_PASSWORD: django
      POSTGRES_USER: django
      POSTGRES_DB: django

  test:
    build: ./
    image: storage-server
    stdin_open: true
    tty: true
    volumes:
      - ./serverless:/usr/local/serverless/serverless/
    command: >
      sh -c "pipenv run coverage run --source='.' manage.py test && pipenv run coverage html"
    depends_on:
      - db