# Generated by Django 4.0 on 2021-12-16 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('80ec2282-8bdd-4db3-97f4-ddc9582ab515'), primary_key=True, serialize=False),
        ),
    ]
