# Generated by Django 4.0 on 2021-12-20 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
