# Generated by Django 3.2.7 on 2021-09-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0007_delete_itemfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('installed', 'Installed'), ('delivered', 'Delivered'), ('out', 'Out'), ('error', 'Error')], default='pending', help_text='Current storage status', max_length=128),
        ),
    ]
