# Generated by Django 3.2.7 on 2021-09-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0008_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
